In [ ]:
贝叶斯定理
    - 全概率公式
    - 贝叶斯公式
朴素贝叶斯算法

In [ ]:
所有特征之间都是独立的，分类原理就是利用贝叶斯公式
根据某对象的先验概率计算出其后验概率，然后选择具有
最大后验概率的类作为该对象所属的类。

In [ ]:
长相帅气
性格好
身高高
上进

# 高斯朴素贝叶斯

In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import  train_test_split
from sklearn.metrics import accuracy_score

from sklearn import datasets
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [2]:
x = iris.data

In [3]:
y = iris.target

In [5]:
from sklearn.preprocessing import label_binarize

In [9]:
from sklearn.preprocessing import label_binarize
y = label_binarize([1, 6], classes=[1, 2, 4, 6])
y

array([[1, 0, 0, 0],
       [0, 0, 0, 1]])

In [8]:
Xtrain,Xtest,ytrain,ytest = train_test_split(iris.data,iris.target,random_state=17)

In [ ]:
len(Xtrain)

In [ ]:
clf = GaussianNB()
clf.fit(Xtrain,ytrain)

In [ ]:
#在测试集上执行预测，proba导出的是每个样本属于某类的概率
clf.predict(Xtest)# 预测的是类别
clf.predict_proba(Xtest)#每一类的概率

In [ ]:
accuracy_score(ytest,clf.predict(Xtest))#准确率

In [ ]:
# 多项式分布的朴素贝叶斯

In [ ]:
# 实例

In [ ]:
# 1导入数据
# 打乱索引-随机切分数据集
import numpy as np
import pandas as pd
import random
dataSet =pd.read_csv('iris.txt',header = None)
dataSet.head()

In [ ]:
# 2切分数据集和训练集
def randSplit(dataSet,rate):

    l = list(dataSet.index) #提取出索引
    random.shuffle(l) #随机打乱索引,只改变索引，不改变原数据
    dataSet.index = l #将打乱后的索引重新赋值给原数据集
    n = dataSet.shape[0] #总行数
    m = int(n * rate) #训练集的数量
    train = dataSet.loc[range(m), :] #提取前m个记录作为训练集
    test = dataSet.loc[range(m, n), :] #剩下的作为测试集
    dataSet.index = range(dataSet.shape[0]) #更新原数据集的索引
    test.index = range(test.shape[0]) #更新测试集的索引
    return train, test

In [ ]:
train,test = randSplit(dataSet,0.8)
train

In [ ]:
#划分数据集分步走
l = list(dataSet.index)# 提取索引

In [ ]:
#打乱
random.shuffle(l)

In [ ]:
dataSet.index = l

In [ ]:
l

In [ ]:
n = dataSet.shape[0]
m = int(n*0.8)# 切分训练集

In [ ]:
dataSet.loc[range(m),:]

In [ ]:
test = dataSet.loc[range(m,n),:]

In [ ]:
test.index = range(test.shape[0])
test

In [ ]:
# 3 构建分类器
def gnb_classify(train,test):
    labels = train.iloc[:,-1].value_counts().index #提取训练集的标签种类
    mean =[] #存放每个类别的均值
    std =[] #存放每个类别的方差
    result = [] #存放测试集的预测结果
    for i in labels:
        item = train.loc[train.iloc[:,-1]==i,:] #分别提取出每一种类别
        m = item.iloc[:,:-1].mean() #当前类别的平均值
        s = np.sum((item.iloc[:,:-1]-m)**2)/(item.shape[0]) #当前类别的方差
        mean.append(m) #将当前类别的平均值追加至列表
        std.append(s) #将当前类别的方差追加至列表
    means = pd.DataFrame(mean,index=labels) #变成DF格式，索引为类标签
    stds = pd.DataFrame(std,index=labels) #变成DF格式，索引为类标签
    for j in range(test.shape[0]):
        iset = test.iloc[j,:-1].tolist() #当前测试实例
        iprob = np.exp(-1*(iset-means)**2/(stds*2))/(np.sqrt(2*np.pi*stds)) #正态分布公式
        prob = 1      #初始化当前实例总概率
        for k in range(test.shape[1]-1): #遍历每个特征
            prob *= iprob[k] #特征概率之积即为当前实例概率
            cla = prob.index[np.argmax(prob.values)] #返回最大概率的类别
        result.append(cla)
    test['predict']=result
    acc = (test.iloc[:,-1]==test.iloc[:,-2]).mean() #计算预测准确率
    print(f'模型预测准确率为{acc}')
    return test

In [ ]:
gnb_classify(train,test)

In [ ]:
#提取训练集的标签种类
labels = train.iloc[:,-1].value_counts().index
mean = []  #每个类别的均值
std=[]     #每个类别的方差
result=[]  #测试集的预测结果


In [ ]:
#求每一类的方差和均值
for i in labels:
    item = train.loc[train.iloc[:,-1]==i,:]# 提取每一个类别

In [ ]:
item = train.loc[train.iloc[:,-1]=='Iris-setosa',:]

In [ ]:
item

In [ ]:
m=item.iloc[:,:-1].mean()

In [ ]:
np.sum((item.iloc[:,:-1]-m)**2)/item.shape[0]

In [ ]:
help(np.argmax)

In [ ]:
# 1 文档分类
过滤器：将不当内容过滤掉
- 把文本看成单词向量
- 考虑出现所有文档中的单词，再决定将哪些单词纳入词汇表或者说所要的词汇集合，
- 将每一篇文档转换为词汇表上的向量。
- 分类标注

### 构建词向量
- loadDataSet：创建实验数据集
- createVocabList：生成词汇表
- setOfWords2Vec：生成词向量
- get_trainMat：所有词条向量列表
- trainNB：朴素贝叶斯分类器训练函数
- classifyNB：朴素贝叶斯分类器分类函数
- testingNB：朴素贝叶斯测试函数

In [1]:
#1 创建数据集
def loadDataSet():
    dataSet=[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
        ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
        ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
        ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
        ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop',
        'him'],
        ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']] #切分好的词条
   
    classVec = [0,1,0,1,0,1] #类别标签向量，1代表侮辱性词汇，0代表非侮辱性词汇
    return dataSet,classVec

In [2]:
dataSet,classVec=loadDataSet()
dataSet,classVec

([['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
  ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
  ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
  ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
  ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
  ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']],
 [0, 1, 0, 1, 0, 1])

In [3]:
# 2 生成词汇表
def createVocabList(dataSet):
    vocabSet = set() #创建一个空的集合
    for doc in dataSet: #遍历dataSet中的每一条言论
        vocabSet = vocabSet | set(doc) #取并集
        vocabList = list(vocabSet)
    return vocabList

In [4]:
vocabList = createVocabList(dataSet)
vocabList     #返回列表

['not',
 'worthless',
 'ate',
 'is',
 'licks',
 'has',
 'stupid',
 'help',
 'flea',
 'posting',
 'so',
 'maybe',
 'buying',
 'cute',
 'stop',
 'garbage',
 'please',
 'steak',
 'how',
 'take',
 'dalmation',
 'my',
 'dog',
 'park',
 'problems',
 'him',
 'mr',
 'to',
 'food',
 'love',
 'quit',
 'I']

In [ ]:
# 3获得训练集向量

In [5]:
#词向量：词条向量化
#根据词汇表将切分好的词条向量化，向量的每个元素为1或0
def setOfWords2Vec(vocabList, inputSet):
    returnVec = [0] * len(vocabList)      #创建一个其中所含元素都为0的向量
    for word in inputSet:                 #遍历每个词条
        if word in vocabList:             #如果词条存在于词汇表中，则变为1
            returnVec[vocabList.index(word)] = 1
        else:
            print(f" {word} is not in my Vocabulary!" )
    return returnVec 

In [6]:
#词条向量列表
def get_trainMat(dataSet):
    trainMat = []                                     #初始化向量列表
    vocabList = createVocabList(dataSet)              #生成词汇表
    for inputSet in dataSet:                          #遍历样本词条中的每一条样本
        returnVec=setOfWords2Vec(vocabList, inputSet) #将当前词条向量化
        trainMat.append(returnVec) #追加到向量列表中
    return trainMat

In [7]:
trainMat = get_trainMat(dataSet)
print(len(trainMat))

6


In [ ]:
#分类器训练函数

In [18]:
#训练集的文档数据
'''
trainMat: 训练文档矩阵
classVec: 训练类别标签向量（分类好的标签）
p0V: 非侮辱类的条件概率数组
p1V: 侮辱类的条件概率数组
pAb: 文档属于侮辱类的概率
'''
    
def trainNB(trainMat,classVec):
    n = len(trainMat)                     #计算训练的文档数目
    m = len(trainMat[0])                  #计算每篇文档的词条数
    pAb = sum(classVec)/n                 #文档属于侮辱类的概率
    p0Num = np.zeros(m)                   #词条出现数初始化为0
    p1Num = np.zeros(m)                   #词条出现数初始化为0
    p0Denom = 0                           #分母初始化为0
    p1Denom = 0                           #分母初始化为0
    for i in range(n):                    #遍历每一个文档
        if classVec[i] == 1:              #统计属于侮辱类的条件概率所需的数据
            p1Num += trainMat[i]
            p1Denom += sum(trainMat[i])
        else:                             #统计属于非侮辱类的条件概率所需的数据
            p0Num += trainMat[i]
            p0Denom += sum(trainMat[i])
    p1V = p1Num/p1Denom
    p0V = p0Num/p0Denom
    return p0V,p1V,pAb                    #返回属于非侮辱类,侮辱类和文档属于侮辱类的概率

In [19]:
p0V,p1V,pAb = trainNB(trainMat,classVec)
p0V,p1V,pAb

(array([0.        , 0.        , 0.04166667, 0.04166667, 0.04166667,
        0.04166667, 0.        , 0.04166667, 0.04166667, 0.        ,
        0.04166667, 0.        , 0.        , 0.04166667, 0.04166667,
        0.        , 0.04166667, 0.04166667, 0.04166667, 0.        ,
        0.04166667, 0.125     , 0.04166667, 0.        , 0.04166667,
        0.08333333, 0.04166667, 0.04166667, 0.        , 0.04166667,
        0.        , 0.04166667]),
 array([0.05263158, 0.10526316, 0.        , 0.        , 0.        ,
        0.        , 0.15789474, 0.        , 0.        , 0.05263158,
        0.        , 0.05263158, 0.05263158, 0.        , 0.05263158,
        0.05263158, 0.        , 0.        , 0.        , 0.05263158,
        0.        , 0.        , 0.10526316, 0.05263158, 0.        ,
        0.05263158, 0.        , 0.05263158, 0.05263158, 0.        ,
        0.05263158, 0.        ]),
 0.5)

In [20]:
# 测试分类器
from functools import reduce 

In [21]:
def classifyNB(vec2Classify, p0V, p1V, pAb):
    p1 = reduce(lambda x,y:x*y, vec2Classify * p1V) * pAb #对应元素相乘
    p0 = reduce(lambda x,y:x*y, vec2Classify * p0V) * (1 - pAb)
    print('p0:',p0)
    print('p1:',p1)
    if p1 > p0:
        return 1
    else:
        return 0

In [22]:
# 测试函数 
def testingNB(testVec):
    dataSet,classVec = loadDataSet() #创建实验样本
    vocabList = createVocabList(dataSet) #创建词汇表
    trainMat= get_trainMat(dataSet) #将实验样本向量化
    p0V,p1V,pAb = trainNB(trainMat,classVec) #训练朴素贝叶斯分类器，得到分类结果
    thisone = setOfWords2Vec(vocabList, testVec) #测试样本向量化
    if classifyNB(thisone,p0V,p1V,pAb)==1:
        print(testVec,'属于侮辱类') #执行分类并打印分类结果
    else:
        print(testVec,'属于非侮辱类')

In [23]:
testVec1 = ['love','my','dalmation']
testingNB(testVec1)

p0: 0.0
p1: 0.0
['love', 'my', 'dalmation'] 属于非侮辱类


In [24]:
# 有问题，初始为0，乘积肯定为0
testVec2 = ['stupid','garbage']
testingNB(testVec1)

p0: 0.0
p1: 0.0
['love', 'my', 'dalmation'] 属于非侮辱类


In [25]:
# 修正：拉普拉斯平滑
def trainNB(trainMat,classVec):
    n = len(trainMat) #计算训练的文档数目
    m = len(trainMat[0]) #计算每篇文档的词条数
    pAb = sum(classVec)/n #文档属于侮辱类的概率
    p0Num = np.ones(m) #词条出现数初始化为1
    p1Num = np.ones(m) #词条出现数初始化为1
    p0Denom = 2 #分母初始化为2
    p1Denom = 2 #分母初始化为2
    for i in range(n): #遍历每一个文档
        if classVec[i] == 1: #统计属于侮辱类的条件概率所需的数据
            p1Num += trainMat[i]
            p1Denom += sum(trainMat[i])
        else: #统计属于非侮辱类的条件概率所需的数据
            p0Num += trainMat[i]
            p0Denom += sum(trainMat[i])
    p1V = np.log(p1Num/p1Denom)
    p0V = np.log(p0Num/p0Denom)
    return p0V,p1V,pAb 

In [26]:
import numpy as np
p0V,p1V,pAb = trainNB(trainMat,classVec)
p0V,p1V,pAb

(array([-3.25809654, -3.25809654, -2.56494936, -2.56494936, -2.56494936,
        -2.56494936, -3.25809654, -2.56494936, -2.56494936, -3.25809654,
        -2.56494936, -3.25809654, -3.25809654, -2.56494936, -2.56494936,
        -3.25809654, -2.56494936, -2.56494936, -2.56494936, -3.25809654,
        -2.56494936, -1.87180218, -2.56494936, -3.25809654, -2.56494936,
        -2.15948425, -2.56494936, -2.56494936, -3.25809654, -2.56494936,
        -3.25809654, -2.56494936]),
 array([-2.35137526, -1.94591015, -3.04452244, -3.04452244, -3.04452244,
        -3.04452244, -1.65822808, -3.04452244, -3.04452244, -2.35137526,
        -3.04452244, -2.35137526, -2.35137526, -3.04452244, -2.35137526,
        -2.35137526, -3.04452244, -3.04452244, -3.04452244, -2.35137526,
        -3.04452244, -3.04452244, -1.94591015, -2.35137526, -3.04452244,
        -2.35137526, -3.04452244, -2.35137526, -2.35137526, -3.04452244,
        -2.35137526, -3.04452244]),
 0.5)

In [27]:
def classifyNB(vec2Classify, p0V, p1V, pAb):
    p1 = sum(vec2Classify * p1V) + np.log(pAb)    #对应元素相乘
    p0 = sum(vec2Classify * p0V) + np.log(1- pAb) #对应元素相乘
    if p1 > p0:
        return 1
    else:
        return 0

In [28]:
#测试样本1
testVec1 = ['love', 'my', 'dalmation']
testingNB(testVec1)

['love', 'my', 'dalmation'] 属于非侮辱类


In [29]:
#测试样本2
testVec2 = ['stupid', 'garbage']
testingNB(testVec2)

['stupid', 'garbage'] 属于侮辱类


In [ ]:
dataSet =pd.read_csv('iris.txt')
dataSet

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()
x = iris.data
y = iris.target
x,y

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)
x_train

In [ ]:
from sklearn.naive_bayes import MultinomialNB,GaussianNB
Bys = GaussianNB(var_smoothing = 1e-8)
Bys.fit(x_train,y_train)

In [ ]:
help(GaussianNB)

In [ ]:
import numpy as np
from sklearn import metrics
pred = Bys.predict(x_test)
accuracy = metrics.accuracy_score(y_test,pred)
print(accuracy)

In [ ]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
digits = load_digits()
x = digits.data
y = digits.target
#划分训练集和测试集
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
#创建模型
from sklearn.naive_bayes import MultinomialNB,GaussianNB
Bys = GaussianNB(var_smoothing=1e-8)
Bys.fit(X_train,y_train)

In [ ]:
from sklearn import metrics
p = Bys.predict(X_test)
accuracy = metrics.accuracy_score(y_test,p)
print(accuracy)

In [ ]:
from matplotlib import pyplot as plt
fig = plt.figure(figsize=(6,6))
fig.subplots_adjust(left=0, right=1, bottom=0, top=1)
for i in range(81):
    ax = fig.add_subplot(9,9,i+1, xticks=[], yticks=[])
    ax.imshow(digits.images[i],cmap=plt.cm.binary,interpolation='nearest')
    ax.text(0, 6, str(digits.target[i]))
plt.show

In [ ]:
from sklearn import metrics
p = Bys.predict(X_test)
plt.imshow(X_test[18].reshape(8,8),cmap=plt.cm.binary)

In [ ]:
y_test[18]

In [ ]:
# 准确率
metrics.accuracy_score(y_test,p)